# The base image name from the TLD Makefile
ARG BASE_IMAGE=docker.io/istio/base

# Version is the base image version from the TLD Makefile
ARG BASE_VERSION=latest

FROM ${BASE_IMAGE}:${BASE_VERSION}

COPY mixs /usr/local/bin/

ENTRYPOINT ["/usr/local/bin/mixs", "server"]
CMD ["--configStoreURL=fs:///etc/opt/mixer/configroot","--configStoreURL=k8s://"]
