# The base image name from the TLD Makefile
ARG BASE_IMAGE=docker.io/istio/base

# Version is the base image version from the TLD Makefile
ARG BASE_VERSION=latest

FROM ${BASE_IMAGE}:${BASE_VERSION}
USER 1000:1000
COPY istioctl /usr/local/bin/
ENTRYPOINT ["/usr/local/bin/istioctl"]
