# The base image name from the TLD Makefile
ARG BASE_IMAGE=docker.io/istio/base

# Version is the base image version from the TLD Makefile
ARG BASE_VERSION=latest

# The following section is used as base image if BASE_DISTRIBUTION=default
FROM ${BASE_IMAGE}:${BASE_VERSION} as default

COPY sdsclient /
RUN chmod 755 /sdsclient
ENTRYPOINT ["/sdsclient"]
